# Site settings
author: Montensia Banks
title: My Code Learning Blog Experience
header-img: img/home-bg.png
email: montensia1@outlook.com
copyright_name: Montensia Banks
description: > # this means to ignore newlines until "baseurl:"
  My code experience
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Monty7

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
